spring:
  datasource:
    url: jdbc:postgresql://localhost:2345/postgres_db
    username: piseth168
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
    port: 4444
